### ISSUE TITLE
Not correctly rendered

### ISSUE THREAD

**Issue by std-microblock** [iBug/TetrisAI#1]
Seems that it cannot work well with Windows Terminal on Windows 11

![image](https://github.com/iBug/TetrisAI/assets/66859419/b5cd2eb7-358e-4828-9413-64a98b5e34cc)

**Comment by iBug** [comment]
This was written when I was still using simplified Chinese on Windows (code page 936) and it targeted `conhost.exe` instead of Windows Terminal. Not sure what I could do with this.

**Comment by std-microblock** [comment]
I'm also using SC. It still works well with conhost.exe, so I guess you can restart it with conhost.

Or just let it go, it's just for fun though :)
